---
title: "Language_correlation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(statsr)
library(ggcorrplot)
library(ppcor)
library(tidyr)
library(ggpubr)
library(ggsignif)
library(psych)
library(gridExtra)
library(rcompanion)
```

## 1.0 clinical

```{r load}
#load clinical data
dfA<-read.csv("clinical_scores_dyad.csv") 

#clean up clinical vars
factors<-c("Date", "Modality", "Therapist", "Patient", "Sex", "Diagnosis", "Telehealth", "Therapist_experience")
dfA[,factors]<-lapply(dfA[,factors], factor)

#restrict to numericals and categoricals and run basic stats
corr_subj<-dfA %>% 
  select_if(is.numeric)

attach(corr_subj)
cor.test(Patient.Alliance, Prev_alliance, method="pearson") 
cor.test(Patient.Alliance, Therapist.Alliance, method="pearson")
cor.test(Therapist.Alliance, Avoidance, method="pearson") 

anova_subj<-df120721[,c(5,16:17,24:25,27)]

wilcox.test(Patient.Alliance ~ Telehealth, anova_subj)
kruskal.test(Patient.Alliance ~ Diagnosis, anova_subj)

#visualize clinical data
GraphicS1A<-ggcorrplot(corr.vars, 
           hc.order = TRUE,
           type = "lower",
           p.mat = p.mat)+
  labs(tag="A")

GraphicS1B<-ggplot(anova_subj, aes(x=Sex, y=Patient.Alliance))+
  geom_violin(trim=FALSE, draw_quantiles = c(0.5))+
  labs(x="Sex",
       y="Patient Alliance",
       tag="B")
GraphicS1C<-ggplot(anova_subj, aes(x=Diagnosis, y=Patient.Alliance))+
  geom_violin(trim=FALSE, draw_quantiles = c(0.5))+
  labs(x="Diagnosis",
       y="Patient Alliance",
       tag="C")
GraphicS1D<-ggplot(anova_subj, aes(x=Therapist_experience, y=Patient.Alliance))+
  geom_violin(trim=FALSE, draw_quantiles = c(0.5))+
  labs(x="Therapist Experience",
       y="Patient Alliance",
       tag="D")
GraphicS1E<-ggplot(anova_subj, aes(x=Modality, y=Patient.Alliance))+
  geom_violin(trim=FALSE, draw_quantiles = c(0.5))+
  labs(x="Modalities",
       y="Patient Alliance",
       tag="E")
GraphicS1F<-ggplot(anova_subj, aes(x=Telehealth, y=Patient.Alliance))+
  geom_violin(trim=FALSE, draw_quantiles = c(0.5))+
  labs(x="Telehealth Session",
       y="Patient Alliance",
       tag="F")

FigureS1<-grid.arrange(GraphicS1A, GraphicS1B, GraphicS1C, 
                       GraphicS1D, GraphicS1E, GraphicS1F,
                       ncol=3, nrow=2)

ggsave("FigS1_Ryu.tiff", FigureS1, width = 10, height = 6)
```

## 2.0 language - pronouns

```{r pressure, echo=FALSE}
# load language data
language <- read.csv("liwcDyadData.csv") 

# divide up frames for specific pronouns data
# subset all dataframes

we <-language[,c('Session','Patient_we','Therapist_we','Patient.Alliance','Goal','Task','Bond')]
we <-pivot_longer(we,
             cols = ends_with("we"),
             names_to = "Role",
             values_to = "Frequency"
             )
we$Role<-as.factor(we$Role)
we$Session <- as.factor(we$Session)

we_t_mean<-colMeans(we[we$Role=="Therapist_we",][,'Frequency'])
we_p_mean<-colMeans(we[we$Role=="Patient_we",][,'Frequency'])
we_t_mean - we_p_mean

i <-language[,c('Session','Patient_i','Therapist_i','Patient.Alliance','Goal','Task','Bond')]
i <-pivot_longer(i,
             cols = ends_with("i"),
             names_to = "Role",
             values_to = "Frequency"
             )
i$Role<-as.factor(i$Role)
i$Session <- as.factor(i$Session)

i_t_mean<-colMeans(i[i$Role=="Therapist_i",][,'Frequency'])
i_p_mean<-colMeans(i[i$Role=="Patient_i",][,'Frequency'])
i_t_mean - i_p_mean

# visualize language data (pronoun) between roles and across alliance

GraphA<-ggplot(we)+
  geom_histogram(data=we[we$Role=="Therapist_we",],
                 aes(x=Frequency, fill = "green"), alpha = 0.5)+
  geom_histogram(data=we[we$Role=="Patient_we",],
                 aes(x=Frequency, fill = "red"), alpha = 0.5)+
  geom_vline(aes(xintercept = we_t_mean), colour="green", linetype=5)+
  geom_vline(aes(xintercept = we_p_mean), colour="red", linetype=5)+
  labs(x="'we' category %",
       y="Frequency",
       tag="A")+
  scale_fill_manual(name="Role", 
                    values=c("green", "red"), 
                    labels=c("Therapist", "Patient")) #put alpha outside of aes if you don't want this part of your legend

GraphB<-ggplot(we[we$Role=="Therapist_we",], aes(x=log(Frequency), y=Patient.Alliance))+
  geom_point()+
  geom_smooth(method="lm")+
  labs(x="Therapist 'we' (a.u.)",
       y="Patient Alliance",
       tag="B")

GraphC<-ggplot(i)+
  geom_histogram(data=i[i$Role=="Therapist_i",],
                 aes(x=Frequency, fill = "green"), alpha = 0.5)+
  geom_histogram(data=i[i$Role=="Patient_i",],
                 aes(x=Frequency, fill = "red"), alpha = 0.5)+
  geom_vline(aes(xintercept = i_t_mean), colour="green", linetype=5)+
  geom_vline(aes(xintercept = i_p_mean), colour="red", linetype=5)+
  labs(x="'i' category %",
       y="Frequency",
       tag="C")+
  scale_fill_manual(name="Role", 
                    values=c("green", "red"), 
                    labels=c("Therapist", "Patient")) 

GraphD<-ggplot(i, aes(x=log(Frequency), y=Patient.Alliance))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap("Role", scales="free_x")+
  labs(x="'i' (a.u.)",
       y="Patient Alliance",
       tag="D")

Figure2<-ggarrange(GraphA, GraphB, 
                      GraphC, GraphD, 
                     ncol=2, nrow=2,
                   common.legend = TRUE, legend="bottom") #readjust to new number of graphs

ggsave("Fig2_Ryu.tiff", Figure2, width = 7, height = 6)

# run stats on pronoun frequency - between roles and across alliance

levels(we$Role)
we$Frequency <- ifelse(we$Frequency==0, 0.01, we$Frequency)
we$logFreq <- log(we$Frequency)
hist(we$logFreq)
t.test(logFreq ~ Role, we, paired=TRUE)

levels(i$Role)
i$Frequency <- ifelse(i$Frequency==0, 0.01, i$Frequency)
i$logFreq <- log(i$Frequency)
hist(i$logFreq)
t.test(logFreq ~ Role, i, paired=TRUE)

attach(i[i$Role=="Patient_i",])
cor.test(logFreq, Patient.Alliance,
         alternative="two.sided",method="pearson", conf.level=0.95)

# bigrams data and correlation with subscores of alliance

pronoun_bigrams <-language[,c('Session','Patient_when_i','Therapist_i_do','Therapist_i_think','Patient.Alliance','Goal','Task','Bond')]
plot(pronoun_bigrams)

# create separate dataframe that has subscores 
subscores <-language[,c('Session','Patient_we','Therapist_we','Patient_i',"Therapist_i",
                        "Patient_AUX.INTJ","Patient_nonflu",
                        'Patient.Alliance','Goal','Task','Bond')]

# dependency between 3 variables (2 subscores, 1 individual language)
# iterate for therapist_we, therapist_i, and patient_i
cor.test(subscores$Goal, subscores$Task,
          method=c("pearson"))->xy
cor.test(subscores$Task, subscores$Bond,
          method=c("pearson"))->yz
cor.test(subscores$Goal, subscores$Bond,
          method=c("pearson"))->xz

cor.test(subscores$Goal, log(subscores$Therapist_we),
          method=c("pearson"))->x1
cor.test(subscores$Task, log(subscores$Therapist_we),
          method=c("pearson"))->y1
cor.test(subscores$Bond, log(subscores$Therapist_we),
          method=c("pearson"))->z1

cor.test(subscores$Goal, log(subscores$Therapist_i),
          method=c("pearson"))->x2
cor.test(subscores$Task, log(subscores$Therapist_i),
          method=c("pearson"))->y2
cor.test(subscores$Bond, log(subscores$Therapist_i),
          method=c("pearson"))->z2

cor.test(subscores$Goal, log(subscores$Patient_i),
          method=c("pearson"))->x3
cor.test(subscores$Task, log(subscores$Patient_i),
          method=c("pearson"))->y3
cor.test(subscores$Bond, log(subscores$Patient_i),
          method=c("pearson"))->z3

# steiger's z test

paired.r(x1$estimate, y1$estimate, xy$estimate, n=28, twotailed=TRUE)
paired.r(x2$estimate, y2$estimate, xy$estimate, n=28, twotailed=TRUE)
paired.r(x3$estimate, y3$estimate, xy$estimate, n=28, twotailed=TRUE)

paired.r(y1$estimate, z1$estimate, yz$estimate, n=28, twotailed=TRUE)
paired.r(y2$estimate, z2$estimate, yz$estimate, n=28, twotailed=TRUE)
paired.r(y3$estimate, z3$estimate, yz$estimate, n=28, twotailed=TRUE)

paired.r(x1$estimate, z1$estimate, xz$estimate, n=28, twotailed=TRUE)
paired.r(x2$estimate, z2$estimate, xz$estimate, n=28, twotailed=TRUE)
paired.r(x3$estimate, z3$estimate, xz$estimate, n=28, twotailed=TRUE) #t=2.27, z=0.03

# create separate dataframes that have PD vs non-PD

levels(dfA$Diagnosis) <- c("Non-PD", "Non-PD", "PD", "Non-PD")

i_PD<-merge(dfA[,c(16,29)], i) #made new dataframes sorted by PD yes/no
we_PD<-merge(dfA[,c(16,29)], we)

# visualize language data (pronoun) between roles and across alliance

subscores_longer <-pivot_longer(subscores,
             cols = c("Goal","Bond"),
             names_to = "Category",
             values_to = "Scores"
             )

GraphicS2A <-ggplot(we_PD[we_PD$Role=="Therapist_we",], aes(x=log(Frequency), y=Patient.Alliance, color=Diagnosis))+
  geom_point()+
  geom_smooth(method="lm")+
  labs(x="Therapist 'we' (a.u.)",
       y="Patient Alliance",
       tag="A")

GraphicS2B<-ggplot(i_PD, aes(x=log(Frequency), y=Patient.Alliance, color=Diagnosis))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap("Role", scales="free_x")+
  labs(x="'i' (a.u.)",
       y="Patient Alliance",
       tag="B")

GraphicS2C<-ggplot(subscores_longer, aes(x=log(Patient_i), y=Scores, color=Category))+
  geom_point()+
  geom_smooth(method="lm")+
  labs(x="Patient 'i' (a.u.)",
       y="Patient Alliance",
       tag="C")

```

## 3.0 language - non-fluency

```{r pressure, echo=FALSE}

# create dataframe for AUX.INTJ and summarize by roles

AUX.INTJ <-language[,c('Session','Patient_AUX.INTJ','Therapist_AUX.INTJ','Patient.Alliance','Goal','Task','Bond',"Number.of.Visits")]
AUX.INTJ <-pivot_longer(AUX.INTJ,
             cols = ends_with("INTJ"),
             names_to = "Role",
             values_to = "Frequency"
             )
AUX.INTJ$Role<-as.factor(AUX.INTJ$Role)
AUX.INTJ$Session <- as.factor(AUX.INTJ$Session)

AUX.INTJ_t_mean<-colMeans(AUX.INTJ[AUX.INTJ$Role=="Therapist_AUX.INTJ",][,'Frequency'])
AUX.INTJ_p_mean<-colMeans(AUX.INTJ[AUX.INTJ$Role=="Patient_AUX.INTJ",][,'Frequency'])
AUX.INTJ_t_mean - AUX.INTJ_p_mean

# create dataframe for disfluency and summarize by roles

disfluency <-language[,c('Session','Patient_nonflu','Therapist_nonflu',
                         'Therapist_and_and','Patient_and_and',
                         'Therapist_okay_okay','Therapist_yeah_yeah', 
                         'Therapist_i_do', 'Therapist_i_think',
                         'Patient.Alliance','Goal','Task','Bond', 'Therapist.Alliance')]

disfluency <- pivot_longer(disfluency,
             cols = ends_with("nonflu"),
             names_to = "Role",
             values_to = "Frequency"
             )

disfluency$Role<-as.factor(disfluency$Role)
disfluency$Session <- as.factor(disfluency$Session)

disfluency_t_mean<-colMeans(disfluency[disfluency$Role=="Therapist_nonflu",][,'Frequency'])
disfluency_p_mean<-colMeans(disfluency[disfluency$Role=="Patient_nonflu",][,'Frequency'])
disfluency_t_mean - disfluency_p_mean

# save select columsn as supplementary table 2

TableS2<-disfluency[,c(4:10)]
write.csv(TableS2, "TableS2_Ryu.csv")

# visualize language data (non-fluency) between roles and across alliance

GraphE<-ggplot(AUX.INTJ)+
  geom_histogram(data=AUX.INTJ[AUX.INTJ$Role=="Therapist_AUX.INTJ",],
                 aes(x=Frequency, fill = "green"), alpha = 0.5)+
  geom_histogram(data=AUX.INTJ[AUX.INTJ$Role=="Patient_AUX.INTJ",],
                 aes(x=Frequency, fill = "red"), alpha = 0.5)+
  geom_vline(aes(xintercept = AUX.INTJ_t_mean), colour="green", linetype=5)+
  geom_vline(aes(xintercept = AUX.INTJ_p_mean), colour="red", linetype=5)+
  labs(x="AUX-INTJ Transition Probability",
       y="Frequency",
       tag="A")+
  scale_fill_manual(name="Role", 
                    values=c("green", "red"), 
                    labels=c("Therapist", "Patient")) 

GraphF<-ggplot(AUX.INTJ[AUX.INTJ$Role=="Patient_AUX.INTJ",], 
               aes(x=Frequency, y=Patient.Alliance))+
  geom_point()+
  geom_smooth(method="lm")+
  labs(x="Patient: AUX-INTJ Transition Probability",
       y="Patient Alliance",
       tag="B")

GraphG<-ggplot(disfluency)+
  geom_histogram(data=disfluency[disfluency$Role=="Therapist_nonflu",],
                 aes(x=Frequency, fill = "green"), alpha = 0.5)+
  geom_histogram(data=disfluency[disfluency$Role=="Patient_nonflu",],
                 aes(x=Frequency, fill = "red"), alpha = 0.5)+
  geom_vline(aes(xintercept = disfluency_t_mean), colour="green", linetype=5)+
  geom_vline(aes(xintercept = disfluency_p_mean), colour="red", linetype=5)+
  labs(x="Nonfluent %",
       y="Frequency",
       tag="C")+
  scale_fill_manual(name="Role", 
                    values=c("green", "red"), 
                    labels=c("Therapist", "Patient")) 

GraphH<-ggplot(disfluency[disfluency$Role=="Patient_nonflu",], 
               aes(x=log(Frequency), y=Patient.Alliance))+
  geom_point()+
  geom_smooth(method="lm")+
  labs(x="Patient 'nonfluent' (a.u.)",
       y="Patient Alliance",
       tag="D")

Figure3 <- ggarrange(GraphE, GraphF, GraphG, GraphH, 
                   ncol=2, nrow=2,
                   common.legend = TRUE, legend="bottom") #readjust to new number of graphs

ggsave("Fig3_Ryu.tiff", Figure3, width = 7, height = 6)

# run non-parametric stats to test paired dependent group difference between roles

levels(AUX.INTJ$Role)
wilcox.test(Frequency ~ Role, AUX.INTJ)
wilcoxonR(x = AUX.INTJ$Frequency,
          g = AUX.INTJ$Role)

# partial correlation: alliance ~ AUX.INTJ by number of visits
# correlation: AUX.INTJ ~ number of visits

pcor.test(AUX.INTJ$Patient.Alliance, AUX.INTJ$Patient_AUX.INTJ, log(AUX.INTJ$Number.of.Visits), method=c("spearman")) #log of aux.intj makes it worse..

GraphicS2D<-ggplot(language, aes(x=log(Number.of.Visits), y=Patient_AUX.INTJ))+
  geom_point()+
  geom_smooth(method="lm")+
  labs(x="Duration of Treatment",
       y="Patient: AUX-INTJ Transition Probability",
       tag="D") 

cor.test(log(AUX.INTJ$Number.of.Visits), AUX.INTJ$Patient_AUX.INTJ,
         alternative="two.sided",method="spearman", conf.level=0.95) 

# run stats to test group difference between roles in disfluency

disfluency$logFreq <- log(disfluency$Frequency)
hist(disfluency$logFreq)
t.test(logFreq ~ Role, disfluency, paired=TRUE)

attach(disfluency[disfluency$Role=="Patient_nonflu",])
cor.test(logFreq, Patient.Alliance,
         alternative="two.sided",method="pearson", conf.level=0.95)

# Are dependent correlations with goal-task differentially impacted by any one of the two disfluencis ?

cor.test(subscores$Goal, subscores$Patient_AUX.INTJ,
          method=c("pearson"))->x4
cor.test(subscores$Task, subscores$Patient_AUX.INTJ,
          method=c("pearson"))->y4
cor.test(subscores$Bond, subscores$Patient_AUX.INTJ,
          method=c("pearson"))->z4

cor.test(subscores$Goal, log(subscores$Patient_nonflu),
          method=c("pearson"))->x5
cor.test(subscores$Task, log(subscores$Patient_nonflu),
          method=c("pearson"))->y5
cor.test(subscores$Bond, log(subscores$Patient_nonflu),
          method=c("pearson"))->z5

# Steiger's Z

paired.r(x4$estimate, y4$estimate, xy$estimate, n=28, twotailed=TRUE)
paired.r(x5$estimate, y5$estimate, xy$estimate, n=28, twotailed=TRUE)

paired.r(y4$estimate, z4$estimate, yz$estimate, n=28, twotailed=TRUE)
paired.r(y5$estimate, z5$estimate, yz$estimate, n=28, twotailed=TRUE)

paired.r(x4$estimate, z4$estimate, xz$estimate, n=28, twotailed=TRUE)
paired.r(x5$estimate, z5$estimate, xz$estimate, n=28, twotailed=TRUE)

# Create Supplementary Fig 2

library(gridExtra)
FigureS2<-grid.arrange(GraphicS2A, GraphicS2B, GraphicS2C, GraphicS2D, nrow=2, ncol=2)
ggsave("FigS2_Ryu.tiff", FigureS2, width = 8 , height = 6)

# Create Supplementary Table 3
allF<-read.csv("metricsFtest.csv")
as.factor(allF$metric)->allF$metric
as.factor(allF$feature)->allF$feature
summary(allF$metric)

select<-c("Therapist_and_and","Therapist_we","Patient_when_i","Patient_AUX,INTJ","Therapist_pronoun_we","Patient_CCONJ,CCONJ","Therapist_ADP,ADP","Therapist_i","Therapist_okay_okay","Therapist_i_do","Patient_ADV,INTJ","Patient_INTJ,PRON","Therapist_CCONJ,CCONJ","Therapist_i_think","Patient_i","Therapist_yeah_yeah","Patient_PRON,PRON","Therapist_INTJ,SCONJ","Patient_nonflu","Patient_and_and")
select2<-c("Therapist Alliance")

# mark those to be selected
allF<-allF %>% 
  mutate(significant = case_when(
    feature %in% select & metric %in% select2 ~ "yes")
  )

b<-allF[allF$significant=="yes",2:5]
b<-b[complete.cases(b),]
b_raw<-language[,c("Patient.Alliance","Diagnosis","Modality","Anxiety","Avoidance","Number.of.Visits","Age","Therapist_ADP.ADP","Patient_PRON.PRON","Patient_INTJ.PRON","Patient_and_and","Patient_CCONJ.CCONJ","Therapist_yeah_yeah","Patient_AUX.INTJ")]

write.csv(b, "TableS3_Ryu.csv")

# run extra stats to see if any of non-alliance clinical variable is correlated with disfluency

plot(b_raw$Anxiety, b_raw$Patient_INTJ.PRON)
cor.test(b_raw$Patient_INTJ.PRON, b_raw$Anxiety, method = "spearman") # 0.04

plot(b_raw$Avoidance, b_raw$Patient_CCONJ.CCONJ)
cor.test(b_raw$Patient_CCONJ.CCONJ, b_raw$Avoidance, method="spearman") # 0.03

plot(b_raw$Number.of.Visits, b_raw$Therapist_yeah_yeah)
cor.test(b_raw$Therapist_yeah_yeah, log(b_raw$Number.of.Visits), method="spearman") # not normal

wilcox.test(Patient_PRON.PRON ~ Modality, b_raw)
levels(b_raw$Modality) <- c("Cognitive_Behavioral", "Supportive_Expressive", "Supportive_Expressive")
str(b_raw$Modality)
b_raw$Modality<-as.factor(b_raw$Modality)

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
